import { ethers } from "hardhat";

const PROFILE_NFT_ADDRESS = "0x22bAA86361451Aec9485D1dE31f05a9674353FC1";
const REPUTATION_CARD_ADDRESS = "0x23DD5EeC3259A02B82ae9680D74D3596B6749aac";
const USER_PRIVATE_KEY = "0x70ac2c425e6fcc912e3a4db90993b3563582557f0c79d9d565f6f6145171b8b6";

// EIP-712 Domain
const EIP712_DOMAIN = {
  name: 'TrustFi ReputationCard',
  version: '1',
  chainId: 1287,
  verifyingContract: REPUTATION_CARD_ADDRESS
};

const EIP712_TYPES = {
  Claim: [
    { name: 'user', type: 'address' },
    { name: 'templateId', type: 'uint256' },
    { name: 'nonce', type: 'uint256' }
  ]
};

async function main() {
  // Create wallet from the user's private key
  const provider = ethers.provider;
  const userWallet = new ethers.Wallet(USER_PRIVATE_KEY, provider);
  
  console.log("Testing claim for user:", userWallet.address);
  console.log("\n=== STEP 1: Check Profile ===");

  const profileNFT = await ethers.getContractAt("ProfileNFT", PROFILE_NFT_ADDRESS);
  const profileId = await profileNFT.addressToProfileId(userWallet.address);
  
  console.log("Profile ID:", profileId.toString());
  
  if (profileId === 0n) {
    console.log("❌ No profile found!");
    return;
  }
  console.log("✅ Profile exists");

  console.log("\n=== STEP 2: Check Template ===");
  
  const reputationCard = await ethers.getContractAt("ReputationCard", REPUTATION_CARD_ADDRESS);
  const template = await reputationCard.templates(1);
  
  console.log("Template #1:");
  console.log("  Issuer:", template.issuer);
  console.log("  Current Supply:", template.currentSupply.toString());
  
  if (template.issuer === ethers.ZeroAddress) {
    console.log("❌ Template does not exist!");
    return;
  }
  console.log("✅ Template exists");

  console.log("\n=== STEP 3: Generate Signature (as issuer) ===");
  
  // Get the issuer wallet (deployer)
  const [issuer] = await ethers.getSigners();
  console.log("Issuer address:", issuer.address);
  
  const userAddress = userWallet.address;
  const templateId = 1;
  const nonce = Date.now();
  
  const messageToSign = {
    user: userAddress,
    templateId: templateId,
    nonce: nonce
  };
  
  console.log("Message to sign:", messageToSign);
  
  // Issuer signs the message
  const signature = await issuer.signTypedData(
    EIP712_DOMAIN,
    EIP712_TYPES,
    messageToSign
  );
  
  console.log("Signature:", signature);
  console.log("✅ Signature generated by issuer");

  console.log("\n=== STEP 4: User Claims with Signature ===");
  
  const tokenURI = "ipfs://QmTest123UserClaim";
  
  console.log("Calling claimWithSignature with:");
  console.log("  _user:", userAddress);
  console.log("  _profileOwner:", userAddress);
  console.log("  _templateId:", templateId);
  console.log("  _nonce:", nonce);
  console.log("  _tokenURI:", tokenURI);
  
  try {
    // User calls the contract
    const reputationCardAsUser = reputationCard.connect(userWallet);
    
    const tx = await reputationCardAsUser.claimWithSignature(
      userAddress,
      userAddress,
      templateId,
      nonce,
      tokenURI,
      signature
    );
    
    console.log("Transaction sent:", tx.hash);
    const receipt = await tx.wait();
    console.log("✅ Transaction confirmed!");
    console.log("Gas used:", receipt.gasUsed.toString());
    
    // Check if card was minted
    const newSupply = await reputationCard.templates(1);
    console.log("New supply:", newSupply.currentSupply.toString());
    
    console.log("\n🎉 SUCCESS! User successfully claimed the collectible!");
    
  } catch (error: any) {
    console.log("❌ Transaction failed!");
    console.log("Error:", error.message);
    
    if (error.data) {
      console.log("Error data:", error.data);
    }
    
    // Try to get more details
    if (error.error) {
      console.log("Error details:", error.error);
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
